### ISSUE TITLE
ask for the implement of the heat map

### ISSUE THREAD

**Issue by wjourney** [yijingru/ASSD-Pytorch#5]
Hello, can you tell me how your heat map is implemented? I am in a hurry, thank you very much.

**Comment by yijingru** [comment]
Hi, I extract the mask and use the some codes similar to below to project the mask on original images:
%%%
hm_show = np.uint8(cv2.applyColorMap(np.uint8(hm[0, :, :] * 255), cv2.COLORMAP_JET))
copy_image = cv2.addWeighted(np.uint8(copy_image), 0.4, hm_show, 0.8, 0)
%%%
If you are asking about how to get attention maps, I just extracted some representative maps from the query locations.
